name: Unit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Run go vet
        run: make vet

      - name: Run golint
        run: make lint

      - name: Run unit tests
        run: make test
